FROM node:18-alpine

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm install

COPY frontend/public ./public
COPY frontend/src ./src
COPY frontend/tailwind.config.js ./
COPY frontend/postcss.config.js ./

EXPOSE 3000

ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

CMD ["npm", "start"]
