FROM node:22-alpine

WORKDIR /app/frontend

RUN npm install -g npm@latest

COPY frontend/package*.json ./
RUN npm install

COPY frontend/public ./public
COPY frontend/src ./src
COPY frontend/index.html ./
COPY frontend/vite.config.js ./
COPY frontend/tailwind.config.js ./
COPY frontend/postcss.config.js ./

EXPOSE 3000

ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

CMD ["npm", "run", "dev"]
