FROM node:22-alpine

WORKDIR /app/backend

RUN npm install -g npm@latest

COPY backend/package*.json ./
RUN npm install

COPY backend/server.js ./
COPY backend/seed.js ./
COPY backend/src ./src

EXPOSE 5000

CMD ["npx", "nodemon", "--watch", "src", "--watch", "server.js", "server.js"]
