FROM node:18-alpine

WORKDIR /app/backend

COPY backend/package*.json ./
RUN npm install

COPY backend/server.js ./
COPY backend/src ./src

EXPOSE 5000

CMD ["npx", "nodemon", "--watch", "src", "--watch", "server.js", "server.js"]
